num = int(input('Digite um número pra ver sua tabuada: '))

print('-' * 12)
print('{} *  1 = {:2}'.format(num, (num * 1)))
print('{} *  2 = {:2}'.format(num, (num * 2)))
print('{} *  3 = {:2}'.format(num, (num * 3)))
print('{} *  4 = {:2}'.format(num, (num * 4)))
print('{} *  5 = {:2}'.format(num, (num * 5)))
print('{} *  6 = {:2}'.format(num, (num * 6)))
print('{} *  7 = {:2}'.format(num, (num * 7)))
print('{} *  8 = {:2}'.format(num, (num * 8)))
print('{} *  9 = {:2}'.format(num, (num * 9)))
print('{} * 10 = {:2}'.format(num, (num * 10)))
print('-' * 12)
